[project]
name = "news-auto"
version = "0.1.0"
description = ""
authors = [
    {name = "jeongkpa"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
